name: cctv

on:
  workflow_dispatch:
  schedule:
    - cron: '0 21 * * *'
  push:
    branches:
      - cctv.py

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: pip install selenium requests futures eventlet aiohttp aiofiles asyncio


      - name: Run cctv
        run: python ${{ github.workspace }}/cctv.py
        
      - name: 提交更改
        run: |
          git config --local user.email "hafrey@163.com"
          git config --local user.name "hafrey1"
          git add .
          git commit *.txt -m "Add generated file"
          git commit *.m3u -m "Add generated file"
          #git pull --rebase
          git push -f
